# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import os
import sys
sys.path.insert(0, os.path.abspath('.'))

from tmconfig import tmconfig


# -- Project information -----------------------------------------------------

project = tmconfig.title
author = tmconfig.author
copyright = f'2021, {author}'

# The full version, including alpha/beta/rc tags
release = "" if tmconfig.version_finale else "intermédiaire"
releasename = "" if tmconfig.version_finale else "Version"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'jupyterlite_sphinx',
    "myst_parser",
    'sphinx_copybutton',
    'sphinx_design',
    'sphinxcontrib.bibtex'
]

# Configure Bibtex
bibtex_bibfiles = ['refs.bib']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_book_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_title = tmconfig.title
html_logo = 'logo.png'
html_favicon = 'favicon.png'

html_theme_options = {
  "home_page_in_toc": True,
  "use_download_button": True,
  "show_navbar_depth": 1,
  "repository_url": tmconfig.repository_url,
  # "use_issues_button": True,
  "use_edit_page_button": True,
}


####### MyST configuration
myst_enable_extensions = ["colon_fence"]


# -- Options for LaTeX output ---------------------------------------------

def add_latex_command(command, latex_raw_string):
    return '\\newcommand{\\' + command + r'}{' + latex_raw_string + '}\n'

def maketitle():
    return r'''
        \pagenumbering{Roman} %%% to avoid page 1 conflict with actual page 1

        \begin{titlepage}
            \centering

            \vspace*{40mm} %%% * is used to give space from top
            \textbf{\Huge {Sphinx format for Latex and HTML}}

            \vspace{0mm}
            \begin{figure}[!h]
                \centering
                \includegraphics[scale=0.3]{logo.jpg}
            \end{figure}

            \vspace{0mm}
            \Large \textbf{{Meher Krishna Patel}}

            \small Created on : Octorber, 2017

            \vspace*{0mm}
            \small  Last updated : \MonthYearFormat\today


            %% \vfill adds at the bottom
            \vfill
            \small \textit{More documents are freely available at }{\href{http://pythondsp.readthedocs.io/en/latest/pythondsp/toc.html}{PythonDSP}}
        \end{titlepage}

        \clearpage
        \pagenumbering{roman}
        \tableofcontents
        \listoffigures
        \listoftables
        \clearpage
        \pagenumbering{arabic}

    '''


latex_elements = {
   'papersize':"a4",
   'author': tmconfig.author,
   'title': tmconfig.title,
   'release' : release,
   'releasename' : releasename,
   'fontpkg': '\\usepackage{times}',
   'babel': '\\usepackage[francais]{babel}',
   #'maketitle': maketitle(),
   'preamble': r'''
        %\usepackage[titles]{tocloft}
        %\cftsetpnumwidth {1.25cm}\cftsetrmarg{1.5cm}
        %\setlength{\cftchapnumwidth}{0.75cm}
        %\setlength{\cftsecindent}{\cftchapnumwidth}
        %\setlength{\cftsecnumwidth}{1.25cm}
        \usepackage{filecontents}
        \usepackage[breaklinks]{hyperref}
        \makeatletter
        \g@addto@macro\UrlBreaks{\do\-}
        \g@addto@macro\UrlBreaks{\do\/}
        \makeatother
   ''' 
    + add_latex_command('seminarytitle', tmconfig.seminary_title)
    + add_latex_command('customizeinfos', r'Modifiez les informations de cette page dans le fichier {\verb tsource/tmconfig.py}' if tmconfig.first_name == 'Prénom' else '')
    + add_latex_command('thedate', tmconfig.date())
    + add_latex_command('theschool', tmconfig.school)
    + add_latex_command('theworktype', tmconfig.worktype),
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'tm-ecrit.tex', tmconfig.title,
   tmconfig.author, 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
latex_show_urls = True

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True
